Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesRating.Data;
using MoviesRating.Models;
using MoviesRating.Services;

namespace MoviesRating.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminController(ApplicationDbContext context)
        {
            _context = context;
        }
        

        // GET: Admin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Admin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Movie model)
        {
            if (ModelState.IsValid)
            {
                var url = model.Tailer;
                model.Tailer = url.Substring(url.IndexOf('=')+1);
                model.PosterPath=Upload.UploadPosterImage(model.PosterFile);
                _context.Add(model);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        // GET: Admin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Admin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Publisher,Rank,PosterPath,Tailer")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Admin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }
    }
}

Controllers/RoleManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoviesRating.Models;
using MoviesRating.ViewModels;
using System.Threading.Tasks;

namespace MoviesRating.Controllers
{
    [Authorize(Roles="SuperAdmin")]
    public class RoleManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RoleManagerController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }
        public async  Task<IActionResult> Index()
        {
            return View(await roleManager.Roles.ToListAsync());
        }

        [HttpPost]

        public async Task<IActionResult> AddRole(RoleViewModel model)
        {

            if(ModelState.IsValid)
            {
                await roleManager.CreateAsync(new IdentityRole(model.Name.Trim()));
            }
            return RedirectToAction("Index");
        }
		public async Task<IActionResult> RemoveRole(string Id)
		{
			var role = await roleManager.Roles.FirstOrDefaultAsync(i => i.Id == Id);
			if (role != null)
			{
				await roleManager.DeleteAsync(role);
			}
			return RedirectToAction("Index");
		}
	}
}

Controllers/UserRolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoviesRating.Models;
using MoviesRating.ViewModels;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net.Mail;
using System.Threading.Tasks;

namespace MoviesRating.Controllers
{
	[Authorize(Roles = "SuperAdmin")]
	public class UserRolesController : Controller
	{
		private readonly UserManager<User> userManager;
		private readonly RoleManager<IdentityRole> roleManager;

		public UserRolesController(UserManager<User> userManager,RoleManager<IdentityRole> roleManager)
        {
			this.userManager = userManager;
			this.roleManager = roleManager;
		}
        public async Task<IActionResult> Index()
		{
			var users = await userManager.Users.ToListAsync();
			var userRolesList = new List<UserViewModel>();
			foreach(var user in users)
			{
				userRolesList.Add(new UserViewModel
				{
					UserId = user.Id,
					FirstName = user.FirstName,
					LastName = user.LastName,
					Email = user.Email,
					UserName = user.UserName,
					Roles = await userManager.GetRolesAsync(user)
				});
			}

			return View(userRolesList);
		}
		[HttpGet]
		public async Task<IActionResult> Manage(string Id)
		{
			var user = await userManager.FindByIdAsync(Id);
			if(user==null)
			{
				ViewBag.ErrorMessage = $"User with Id={Id} cant be found";
				return View("Not Found");
			}
			ViewBag.User = user.UserName;
			List<RoleViewModel> RolesList = new List<RoleViewModel>();
			foreach(var role in roleManager.Roles)
			{
				RolesList.Add(new RoleViewModel
				{
					RoleId=role.Id,
					Name=role.Name,
					IsSelected=await userManager.IsInRoleAsync(user,role.Name),
				});
			}

			return View(RolesList);
		}
		[HttpPost]
		public async Task<IActionResult> Manage(List<RoleViewModel> model,string Id)
		{
			var user = await userManager.FindByIdAsync(Id);
			if (user == null)
			{
				return View();
			}
			var roles = await userManager.GetRolesAsync(user);
			var res = await userManager.RemoveFromRolesAsync(user,roles);
			if(!res.Succeeded)
			{
				ModelState.AddModelError("", "Cant remove prevoues Roles");
				return View(model);
			}
			res = await userManager.AddToRolesAsync(user, model.Where(i => i.IsSelected).Select(i => i.Name));
			if (! res.Succeeded)
			{
				ModelState.AddModelError("", "Cant Add new Roles");
				return View(model);
			}
			ViewBag.User = user.UserName;


			return RedirectToAction(nameof(Index));
		}

		[HttpGet]
		public async Task<IActionResult> Create()
		{
			var model = new UserViewModel();
			model.RolesViewModel = await roleManager.Roles.Select(i=>new RoleViewModel {Name=i.Name,RoleId=i.Id,IsSelected=false }).ToListAsync();

			return View(model);
		}
		[HttpPost]
		public async Task<IActionResult>Create(UserViewModel  model)
		{
			var user = await userManager.Users.FirstOrDefaultAsync(i => i.Email == model.Email);
			if(user!=null)
			{
				ModelState.AddModelError("Email", "Email address Exists.");
				return View(model);
			}
			user = new User
			{
				FirstName = model.FirstName,
				LastName = model.LastName,
				Email = model.Email,
				UserName = new MailAddress(model.Email).User,
				EmailConfirmed = true,

			};
			var res =await userManager.CreateAsync(user,model.Password);
			if(!res.Succeeded)
			{
                ModelState.AddModelError("", "can not add the user");
                return View(model);
            }
			
			foreach(var role in model.RolesViewModel)
			{
				if (role.IsSelected)
					await userManager.AddToRoleAsync(user, role.Name);
			}
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Remove(string Id)
		{
			var user=await userManager.FindByIdAsync(Id);
			if(user!=null)
			{
				await userManager.DeleteAsync(user);
			}
			return RedirectToAction(nameof(Index));
		}

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviesRating</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home"  asp-action="Index">MoviesRating</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if(User.IsInRole(Roles.Admin.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Create">ADD Movie</a>
                            </li>
                        }
                        @if(User.IsInRole(Roles.SuperAdmin.ToString()))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserRoles" asp-action="Index">User Roles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RoleManager" asp-action="Index">Roles</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MoviesRating - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>